# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Full_Name', models.CharField(max_length=120, null=True)),
                ('Phone_No', models.CharField(max_length=13, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Religion', models.CharField(choices=[('HINDUISM', 'Hinduism'), ('CHRISTIANITY', 'Christianity'), ('JUDAISM', 'Judaism'), ('ISLAM', 'Islam'), ('TAOISM', 'Taoism'), ('BUDDHISM', 'Buddhism'), ('SIKHISM', 'Sikhism')], max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
